apiVersion: v1
kind: Service
metadata:
  name: fdb-oms-public
  namespace: foundationdb-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    foundationdb.org/fdb-cluster-name: fdb-oms
  ports:
    - name: tls
      port: 4500
      targetPort: 4500
